### ISSUE TITLE
Cannot buy "OAuth in Action" eBook because Manning's site is broken

### ISSUE THREAD

**Issue by mschilli** [oauthinaction/oauth-in-action-code#11]
Hey guys, would you mind telling Manning that it's currently impossible to buy the book because clicking "add to cart" on the book page [1] does nothing? I've read excerpts and they were great, so I'd really like to purchase the entire eBook. Or is there a way to purchase it off of Manning's site?
[1] https://www.manning.com/books/oauth-2-in-action/

**Comment by jricher** [comment]
We'll pass this along. Sometimes things get a little weird with the company's shopping cart software, and unfortunately it's out of our control. You can also get the book from Amazon: https://www.amazon.com/OAuth-2-Action-Justin-Richer/dp/161729327X/?tag=crfa12-20

**Comment by mschilli** [comment]
Thanks for passing it along, reason I went to the Manning website is that I prefer the PDF format, not the paper book. Hopefully they'll get their shopping cart fixed soon.

**Comment by jricher** [comment]
Thanks for your patience, we definitely understand your frustration. You're not the first or only one to have problems with their site, and that's just those that I know about.

**Comment by jricher** [comment]
Turns out that you need to not have the trailing slash on the URL in order for the shopping cart to work:

https://www.manning.com/books/oauth-2-in-action

**Comment by mschilli** [comment]
I got an email from Manning support this morning with this exact suggestion and purchased the book, thanks! Note that searching for the term "oauth" on their site results in the URL with the trailing slash (!), from where you can't purchase the book, so you might want to ping them again to fix this or lose potential customers.
Just wanted to make sure you guys are compensated fairly for your excellent work, I know from experience how much hard work goes into a book, and can guess how frustrating it must be when a minor technical glitch prevents sales from happening. Best of luck with your sales!
