### ISSUE TITLE
ch-12-ex-2 has a syntax error

### ISSUE THREAD

**Issue by seetdev** [oauthinaction/oauth-in-action-code#17]
The following code has a syntax error
https://github.com/oauthinaction/oauth-in-action-code/blob/23d2e5868a157c29023735a851b7b7b2282b0833/exercises/ch-12-ex-2/authorizationServer.js#L242

The correct code should be `var checkClientMetadata = function(req, res) {`

**Comment by jricher** [comment]
Fixed https://github.com/oauthinaction/oauth-in-action-code/blob/master/exercises/ch-12-ex-2/authorizationServer.js#L241
