### ISSUE TITLE
Use `Buffer.from` instead of `new Buffer`

### ISSUE THREAD

**Issue by johnsonjo4531** [oauthinaction/oauth-in-action-code#27]
On new Node.js versions `new Buffer()` is deprecated `Buffer.from` seems like a better option for the cases that `new Buffer` was used in this book. I get the following error in `authorizationServer.js` and `client.js`

> (node:15865) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

I used Buffer.from in both places and it seems to work just fine.

**Comment by jricher** [comment]
Hopefully fixed by #44, closing for now.
