### ISSUE TITLE
ch-3-ex-2authorizationServe.js bug

### ISSUE THREAD

**Issue by Babagilo** [oauthinaction/oauth-in-action-code#30]
I have to introduce some time gap between nosql.clear() and nosql.insert(), like below:
// clear the database on startup
nosql.clear();
// inject our pre-baked refresh token
setTimeout(() => nosql.insert({ refresh_token: 'j2r3oj32r23rmasd98uhjrk2o3i', client_id: 'oauth-client-1', scope: 'foo bar' }), 5000)

Does anybody know why? Is there any better way to fix this?

**Comment by jricher** [comment]
This seems to be some kind of race condition in the newer version of the nosql library. We've updated the code with the timeout to help with that, and there doesn't seem to be a way to use a promise or callback to schedule the operation.
