### ISSUE TITLE
nosql.one() expects a callback and gets 'undefined'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [oauthinaction/oauth-in-action-code#36]
I've started the tour through "OAuth 2.0 in Action" and begun the exercises in chapter 3. At the end of chapter 3.3 and at the start of chapter 3.4, I've tried to get a protected resource from the server in 'protectedResource.js'. The server crashed, if it tries to call 'nosql.one(..., ...)' with the following error-message:

OAuth Resource Server is listening at http://127.0.0.1:9002
Incoming token: 987tghjkiu6trfghjuytrghj
fs.js:156
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined

**Comment by sosumi** [comment]
This appears to be the same issue as #14. Specifically, the book was written against a (now) significantly dated version of Node, as well as a former version of the (seemingly lightly used) `nosql` module.

The comments on the related issue should point you in the right direction: your options seem to be either to use an outdated version of Node, or to follow the procedure outlined in https://github.com/oauthinaction/oauth-in-action-code/issues/14#issuecomment-475878968.

@artursudnik has a fork of this repository with the fix already applied at https://github.com/artursudnik/oauth-in-action-code.

**Comment by jricher** [comment]
Hopefully fixed by #44, closing for now.
